using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DoctorManager : MonoBehaviour
{
	[Header("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½Ì”ï¿½ï¿½ï¿½")]
	public bool Frieze = false;

	[Header("ï¿½ï¿½ï¿½Cï¿½tï¿½ï¿½ï¿½ï¿½ÏXï¿½Å‚ï¿½ï¿½ï¿½ï¿½")]
	public int Life_Doctor;

	[Header("ï¿½ï¿½ï¿½mï¿½ÌˆÚ“ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ÏXï¿½Å‚ï¿½ï¿½ï¿½ï¿½")]
	public float Speed;
	
	[Header("ï¿½pï¿½[ï¿½cï¿½ÉGï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ì”ï¿½ï¿½ï¿½")]
	public bool OnParts;

	[Header("ï¿½pï¿½[ï¿½cï¿½ï¿½Í‚ï¿½Å‚ï¿½ï¿½é‚©ï¿½Ì”ï¿½ï¿½ï¿½")]
	public bool Catching;

	[Header("ï¿½ï¿½Æ‘ï¿½ÉGï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ì”ï¿½ï¿½ï¿½")]
	public bool OnTable = false;

	[Header("ï¿½Xï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½Ì”ï¿½ï¿½ï¿½")]
	public bool SkillOn = false;

	[Header("ï¿½Xï¿½Lï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½ÏXï¿½Å‚ï¿½ï¿½ï¿½ï¿½")]
	[SerializeField]
	private float Blue_Time, Yellow_Time, Red_Time;

	[Header("ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÌƒXï¿½Lï¿½ï¿½ï¿½Ìcï¿½èï¿½ï¿½")]
	[SerializeField]
	private float SkillTime;

	[Header("ï¿½pï¿½[ï¿½cï¿½ï¿½ï¿½Hï¿½Ìï¿½Æï¿½ï¿½Ô‚ï¿½ÏXï¿½Å‚ï¿½ï¿½ï¿½ï¿½")]
	[SerializeField]
	public float Create_Time;

	[SerializeField]
	GameObject[] Life;

	[Header("ï¿½ï¿½ï¿½ï¿½ï¿½pï¿½Ïï¿½ï¿½`ï¿½Gï¿½ï¿½È‚ï¿½ï¿½Å‚Ë`")]
	[SerializeField]
	private float StickSafety;//ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½Ì”ï¿½ï¿½ï¿½ï¿½Í‚ï¿½ï¿½Ç‚ï¿½ï¿½Ü‚ÅÈ‚ï¿½ï¿½ï¿½
	public string SkillName;//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½Lï¿½ï¿½ï¿½Ìï¿½Ş‚ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½
	public GameObject Hand;//ï¿½ï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½
	public GameObject Parts;//ï¿½Gï¿½ï¿½Ä‚ï¿½ï¿½ï¿½(ï¿½Í‚ï¿½Å‚ï¿½ï¿½ï¿½)ï¿½pï¿½[ï¿½cï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½
	public bool Skill_Keep;//ï¿½pï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½Hï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	public GameObject Zyama;//ï¿½Wï¿½ï¿½ï¿½}ï¿½}ï¿½[ï¿½ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½

	private bool Create_now;//ï¿½ï¿½Æ‚ï¿½ï¿½Ä‚ï¿½ï¿½éï¿½ï¿½true
	public float Createnow_Time = 0;//ï¿½ï¿½Æï¿½ï¿½Ô‚ğ‘ª‚ï¿½pï¿½Ì•Ïï¿½
	Rigidbody rb;
	Animator Am;

	//ï¿½ÅIï¿½ï¿½ï¿½Í‚ï¿½Û‘ï¿½ï¿½ï¿½ï¿½ï¿½Ïï¿½
	Quaternion LastRotation;

	//ï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½Í‚ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½
	float Horizontal;
	float Vertical;

	Vector3 direction;//ï¿½Ú“ï¿½ï¿½Ê‚ï¿½ï¿½iï¿½[ï¿½ï¿½ï¿½ï¿½Ïï¿½

	void Start()
	{
		rb = GetComponent<Rigidbody>();
		Am = GetComponent<Animator>();
		SkillName = null;
	}

	//ï¿½ï¿½ï¿½ÍŒnï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½
	void Update()
	{
		//Friezeï¿½ï¿½trueï¿½ÌŠï¿½(ï¿½|ï¿½[ï¿½Yï¿½ï¿½ï¿½Æ’ï¿½)ï¿½Í‘ï¿½ï¿½ì‚ªï¿½Å‚ï¿½ï¿½È‚ï¿½
		if(Frieze == false)
        {
			//ï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½Í‚ï¿½ï¿½ó‚¯ï¿½ï¿½
			Horizontal = Input.GetAxis("Horizontal_Dr");
			Vertical = Input.GetAxis("Vertical_Dr");
			
			//ï¿½Ú“ï¿½ï¿½Ê‚ÌŒvï¿½Z
			direction = new Vector3(Horizontal, 0, Vertical).normalized * Speed;
			
			//ï¿½ï¿½ï¿½ï¿½ï¿½ÌØ‚ï¿½Ö‚ï¿½
			Turn();

			//ï¿½pï¿½[ï¿½cï¿½ï¿½Í‚Şï¿½ï¿½ï¿½
			Catch();

			//ï¿½pï¿½[ï¿½cï¿½ÉGï¿½ï¿½Ä‚é‚©ï¿½ï¿½ï¿½æ“¾
			OnParts = Hand.GetComponent<DoctorHand>().OnParts;

			//ï¿½Xï¿½Lï¿½ï¿½ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ê‚½ï¿½ï¿½
			if (Input.GetButtonDown("ï¿½ï¿½_Button"))
			{
				Create();
			}
		}

		if (Life_Doctor == 1)
		{
			Destroy(Life[1]);
		}
		if (Life_Doctor == 0)
		{
			Destroy(Life[0]);
		}
	}

	//ï¿½ï¿½ï¿½sï¿½nï¿½Í‚ï¿½ï¿½ï¿½ï¿½ï¿½
	void FixedUpdate()
	{
		if (Frieze == false)
		{
			//ï¿½ï¿½ï¿½Í‚ï¿½ï¿½É‹Í‚ï¿½ï¿½Èê‡ï¿½ÍˆÚ“ï¿½ï¿½Ê‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½
			if (Horizontal >= StickSafety || Vertical >= StickSafety || Horizontal <= -StickSafety || Vertical <= -StickSafety)
			{
				Am.SetBool("Walk",true);

				//ï¿½Ú“ï¿½ï¿½Ê‚ï¿½Uï¿½è“–ï¿½Ä‚ï¿½(ï¿½ï¿½ï¿½Û‚ÉˆÚ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½)ï¿½ï¿½ï¿½ï¿½
				rb.velocity = direction;
			}
			else
            {
				Am.SetBool("Walk", false);

				rb.velocity = new Vector3 (0, 0, 0);
			}
		}
		else
		{
			rb.velocity = new Vector3(0, 0, 0);
		}

		//ï¿½Xï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½s
		if (SkillOn == true)
		{
			Skill();
		}

		//ï¿½ï¿½Æ’ï¿½ï¿½Ìƒtï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½Ìï¿½
		if (Create_now == true)
		{
			Am.SetBool("Build",true);

			//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ó‚¯•tï¿½ï¿½ï¿½È‚ï¿½ï¿½æ‚¤ï¿½É’ï¿½~ï¿½tï¿½ï¿½ï¿½Oï¿½ğ—§‚Ä‚ï¿½
			Frieze = true;

			//ï¿½ï¿½Æï¿½ï¿½Ô‚ÌƒJï¿½Eï¿½ï¿½ï¿½gï¿½_ï¿½Eï¿½ï¿½
			Createnow_Time -= Time.deltaTime;

			//ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ß‚ï¿½ï¿½ï¿½ï¿½ï¿½tï¿½ï¿½ï¿½Oï¿½Ìƒï¿½ï¿½Zï¿½bï¿½g
			if (Createnow_Time <= 0)
			{
				Am.SetBool("Build", false);

				Create_now = false;//ï¿½ï¿½Æ’ï¿½ï¿½tï¿½ï¿½ï¿½O
				Frieze = false;//ï¿½ï¿½~ï¿½tï¿½ï¿½ï¿½O
				Skill_Keep = true;//ï¿½ï¿½ï¿½Hï¿½ï¿½pï¿½[ï¿½cï¿½Ìæ“¾ï¿½ï¿½
			}
		}
	}

	//ï¿½ï¿½ï¿½ï¿½ï¿½Ì•ÏX
	void Turn()
	{
		//ï¿½ï¿½ï¿½Í‚ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é(ï¿½É‹Í‚ï¿½ï¿½È“ï¿½ï¿½Í‚ÍÈ‚ï¿½)
		if (Horizontal >= StickSafety || Vertical >= StickSafety || Horizontal <= -StickSafety || Vertical <= -StickSafety)
		{
			//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÏX
			var direction = new Vector3(Horizontal, 0, Vertical);
			transform.localRotation = Quaternion.LookRotation(direction);

			//ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Û‘ï¿½
			LastRotation = transform.localRotation;
		}
		else
        {
			transform.localRotation = LastRotation;
		}
	}

	//ï¿½pï¿½[ï¿½cï¿½ï¿½Í‚Şï¿½ï¿½ï¿½
	void Catch()
    {
		if(Input.GetButtonDown("ï¿½ï¿½_Button"))
        {
			//ï¿½Gï¿½ï¿½Ä‚ï¿½ï¿½é‚¯ï¿½Ç’Í‚ï¿½Å‚Í‚ï¿½ï¿½È‚ï¿½ï¿½Æ‚ï¿½(ï¿½Í‚ï¿½)
			if(OnParts == true && Catching == false)
            {
				//ï¿½Ç‚Ìƒpï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½é‚©ï¿½ï¿½ï¿½ó‚¯ï¿½ï¿½
				Parts = Hand.GetComponent<DoctorHand>().Parts;

				//ï¿½pï¿½[ï¿½cï¿½É’Í‚ï¿½Å‚ï¿½ï¿½é”»ï¿½ï¿½ğ‘—‚ï¿½
				Catching = Parts.GetComponent<PartsManager>().Catching = true;
            }
			//ï¿½Í‚ï¿½Å‚ï¿½ï¿½é(ï¿½ï¿½ï¿½ï¿½)
			else if(Catching == true)
			{
				//ï¿½pï¿½[ï¿½cï¿½Ì’Í‚ï¿½Å‚ï¿½ï¿½é”»ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½(ï¿½ï¿½ï¿½ï¿½)
				Catching = Parts.GetComponent<PartsManager>().Catching = false;

				//ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½pï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½È‚ï¿½ï¿½ï¿½Ô‚É‚ï¿½ï¿½ï¿½
				Parts = null;
			}
        }

		if(Catching == true)
		{
			Am.SetBool("Hold", true);
		}
		else
        {
			Am.SetBool("Hold", false);
		}
    }

	void Create()
    {
		//ï¿½pï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Aï¿½Xï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Å‚Í‚È‚ï¿½ï¿½Aï¿½ï¿½Æ‘ï¿½ÉGï¿½ï¿½Ä‚ï¿½ï¿½ï¿½Aï¿½ï¿½Æ‚ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½ï¿½pï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½È‚ï¿½ï¿½ï¿½
		if (Catching == true && SkillOn == false && OnTable == true && Skill_Keep == false)
		{
			SkillName = Hand.GetComponent<DoctorHand>().SkillName;//ï¿½Xï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½æ“¾

			//ï¿½Xï¿½Lï¿½ï¿½ï¿½Ì”ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½æ“¾
			switch (SkillName)
			{
				case "Blue":
					SkillTime = Blue_Time;
					break;

				case "Yellow":
					SkillTime = Yellow_Time;
					break;

				case "Red":
					SkillTime = Red_Time;
					break;
			}
			Createnow_Time = Create_Time;//ï¿½ï¿½Æ—pï¿½ÌƒJï¿½Eï¿½ï¿½ï¿½gï¿½_ï¿½Eï¿½ï¿½ï¿½ï¿½İ’ï¿½Eï¿½Äİ’ï¿½
			Create_now = true;//ï¿½ï¿½Æ’ï¿½ï¿½Ìƒtï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½(ï¿½Iï¿½ï¿½ï¿½ÌŠÔ‚Í“ï¿½ï¿½ï¿½ï¿½È‚ï¿½)
		}
	}

	//ï¿½Xï¿½Lï¿½ï¿½ï¿½Sï¿½Ê‚Ìï¿½ï¿½ï¿½
	void Skill()
	{
		//ï¿½Xï¿½Lï¿½ï¿½ï¿½ï¿½ï¿½Ô‚ÌƒJï¿½Eï¿½ï¿½ï¿½gï¿½_ï¿½Eï¿½ï¿½
		SkillTime -= Time.deltaTime;

		//ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½Lï¿½ï¿½ï¿½Ì‘Iï¿½ï¿½
		switch (SkillName)
        {
			case null:
				break;

			case "Blue":
				Blue_Skill();
				break;

			case "Yellow":
				Yellow_Skill();
				break;

			case "Red":
				Red_Skill();
				break;
        }
		
		//ï¿½ï¿½ï¿½Ô‚ï¿½ï¿½ß‚ï¿½ï¿½ï¿½ï¿½ï¿½Xï¿½Lï¿½ï¿½ï¿½tï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½Iï¿½tï¿½É‚ï¿½ï¿½ï¿½
		if (SkillTime <= 0)
		{
			SkillOn = false;
			SkillName = null;

			Zyama.GetComponent<Jamma>(). Frieze = false;
		}
	}

	void Blue_Skill()//ï¿½ÂƒXï¿½Lï¿½ï¿½
	{

	}

	void Yellow_Skill()//ï¿½ï¿½ï¿½Xï¿½Lï¿½ï¿½
    {
		Zyama.GetComponent<Jamma>().Frieze = true;
	}

	void Red_Skill()//ï¿½ÔƒXï¿½Lï¿½ï¿½
    {
		//ï¿½ï¿½ï¿½Cï¿½ï¿½ï¿½}ï¿½Vï¿½ï¿½ï¿½iï¿½uï¿½ï¿½ï¿½bï¿½Nï¿½jï¿½ï¿½ï¿½{ï¿½[ï¿½ï¿½ï¿½ï¿½ï¿½Í‚Ë•Ô‚ï¿½ï¿½æ‚¤ï¿½É‚È‚ï¿½
	}
}
